version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: 1Panel-redis-checkin
    ports:
      - "6379:6379"
    volumes:
      - /opt/1panel/apps/redis-checkin/data:/data
    restart: unless-stopped
